In [1]:
import pandas as pd
import numpy as np
import os
import math
import csv
import random
from tqdm import tqdm_notebook as tqdm

In [2]:
test_merges = pd.read_csv('/storage/kdd/test_final.csv')

In [3]:
test_merges

,sid,pid,req_time,o,d,plan_time,plans,p0,p1,p2,...,p56,p57,p58,p59,p60,p61,p62,p63,p64,p65
0,1126541,178395.0,2018-12-05 14:51:43,"116.41,39.92","116.46,39.95",2018-12-05 14:51:43,"[{""distance"": 13610, ""price"": 400, ""eta"": 2388...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1389752,178395.0,2018-12-03 17:30:22,"116.40,39.91","116.46,39.95",2018-12-03 17:30:22,"[{""distance"": 10499, ""price"": 400, ""eta"": 2946...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1126543,178395.0,2018-12-05 12:10:43,"116.41,39.92","116.32,39.89",2018-12-05 12:10:43,"[{""distance"": 12277, ""price"": 400, ""eta"": 2319...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,1349248,178395.0,2018-12-04 09:42:37,"116.41,39.91","116.46,39.95",2018-12-04 09:42:37,"[{""distance"": 9710, ""price"": 400, ""eta"": 2270,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1349239,178395.0,2018-12-04 22:49:10,"116.32,39.89","116.41,39.92",2018-12-04 22:49:10,"[{""distance"": 10475, ""price"": 4000, ""eta"": 194...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5,1349241,178395.0,2018-12-04 09:34:17,"116.41,39.91","116.30,39.92",2018-12-04 09:34:17,"[{""distance"": 12438, ""price"": 400, ""eta"": 2247...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
6,1126542,178395.0,2018-12-05 12:08:39,"116.41,39.92","116.46,39.95",2018-12-05 12:08:39,"[{""distance"": 13758, ""price"": 400, ""eta"": 2519...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
7,1349243,178395.0,2018-12-04 09:13:49,"116.41,39.91","116.30,39.92",2018-12-04 09:13:49,"[{""distance"": 12738, ""price"": 1800, ""eta"": 257...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
8,1349244,178395.0,2018-12-04 10:05:37,"116.31,39.91","116.29,39.92",2018-12-04 10:05:37,"[{""distance"": 3245, ""price"": 300, ""eta"": 1137,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9,1126540,178395.0,2018-12-05 15:24:34,"116.46,39.95","116.46,39.95",2018-12-05 15:24:34,"[{""distance"": 458, ""price"": """", ""eta"": 391, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10,1349240,178395.0,2018-12-04 08:51:50,"116.41,39.92","116.29,39.92",2018-12-04 08:51:50,"[{""distance"": 13856, ""price"": 500, ""eta"": 2860...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
11,453685,179178.0,2018-12-01 12:50:33,"116.39,39.90","116.41,39.91",2018-12-01 12:50:33,"[{""distance"": 2858, ""price"": 200, ""eta"": 1798,...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
12,1107620,179178.0,2018-12-05 13:11:30,"116.57,39.91","116.48,39.88",2018-12-05 13:11:30,"[{""distance"": 12615, ""price"": 400, ""eta"": 2650...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
13,1107621,179178.0,2018-12-05 17:37:08,"116.47,39.89","116.31,39.67",2018-12-05 17:37:08,"[{""distance"": 37332, ""price"": 700, ""eta"": 3962...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14,1107618,179178.0,2018-12-05 13:14:29,"116.57,39.91","116.48,39.88",2018-12-05 13:14:29,"[{""distance"": 12583, ""price"": 400, ""eta"": 2621...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
15,1349032,179178.0,2018-12-04 22:12:58,"116.30,39.62","116.29,39.87",2018-12-04 22:12:58,"[{""distance"": 34150, ""price"": """", ""eta"": 2078,...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
16,1437724,179178.0,2018-12-06 14:29:56,"116.40,39.97","116.41,39.96",2018-12-06 14:29:56,"[{""distance"": 1348, ""price"": """", ""eta"": 1171, ...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
17,2066073,184748.0,2018-12-07 10:17:35,"116.37,39.71","116.31,39.89",2018-12-07 10:17:35,"[{""distance"": 33453, ""price"": 800, ""eta"": 5624...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,452746,162795.0,2018-12-01 07:52:44,"116.33,39.97","116.31,39.98",2018-12-01 07:52:44,"[{""distance"": 4007, ""price"": 1500, ""eta"": 989,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19,452745,162795.0,2018-12-01 07:57:29,"116.32,39.96","116.31,39.98",2018-12-01 07:57:29,"[{""distance"": 2650, ""price"": 300, ""eta"": 961, ...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
20,1431672,116384.0,2018-12-06 10:36:30,"116.51,39.68","116.51,39.68",2018-12-06 10:36:30,"[{""distance"": 692, ""price"": """", ""eta"": 591, ""t...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
21,2060796,116384.0,2018-12-07 15:57:48,"116.42,39.82","116.42,39.82",2018-12-07 15:57:48,"[{""distance"": 864, ""price"": """", ""eta"": 740, ""t...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
22,2060799,116384.0,2018-12-07 14:51:03,"116.41,39.91","116.41,39.84",2018-12-07 14:51:03,"[{""distance"": 10487, ""price"": 400, ""eta"": 1994...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
23,1431678,116384.0,2018-12-06 09:09:51,"116.44,39.84","116.51,39.68",2018-12-06 09:09:51,"[{""distance"": 24286, ""price"": 2900, ""eta"": 517...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
24,2060795,116384.0,2018-12-07 08:46:50,"116.65,40.13","116.31,39.98",2018-12-07 08:46:50,"[{""distance"": 43240, ""price"": 700, ""eta"": 5135...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
25,1431680,116384.0,2018-12-06 07:55:19,"116.43,39.85","116.31,39.98",2018-12-06 07:55:19,"[{""distance"": 27894, ""price"": 600, ""eta"": 4549...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
26,2060792,116384.0,2018-12-07 15:44:03,"116.42,39.84","116.42,39.82",2018-12-07 15:44:03,"[{""distance"": 4413, ""price"": 200, ""eta"": 1840,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
27,2060797,116384.0,2018-12-07 09:37:00,"116.40,40.00","116.31,39.97",2018-12-07 09:37:00,"[{""distance"": 11058, ""price"": 400, ""eta"": 2134...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
28,1128839,116384.0,2018-12-05 22:42:57,"116.59,40.08","116.51,39.68",2018-12-05 22:42:57,"[{""distance"": 60445, ""price"": """", ""eta"": 3998,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
29,1128838,116384.0,2018-12-05 22:43:20,"116.59,40.08","116.51,39.68",2018-12-05 22:43:20,"[{""distance"": 60445, ""price"": """", ""eta"": 4000,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94328,1393550,176518.0,2018-12-03 19:27:37,"116.39,39.98","116.40,39.93",2018-12-03 19:27:37,"[{""distance"": 7038, ""price"": 400, ""eta"": 1402,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
94329,1415669,216654.0,2018-12-06 12:06:45,"116.64,40.34","116.59,40.92",2018-12-06 12:06:45,"[{""distance"": 87930, ""price"": """", ""eta"": 5486,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94330,1108383,103104.0,2018-12-05 21:53:43,"116.46,39.94","116.47,39.93",2018-12-05 21:53:43,"[{""distance"": 2449, ""price"": 200, ""eta"": 1807,...",0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
94331,1279336,161440.0,2018-12-02 09:05:42,"116.34,39.71","116.42,39.90",2018-12-02 09:05:42,"[{""distance"": 30671, ""price"": 800, ""eta"": 5450...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94332,1423005,188097.0,2018-12-06 14:24:31,"116.40,40.00","116.32,39.89",2018-12-06 14:24:31,"[{""distance"": 23618, ""price"": 500, ""eta"": 4315...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94333,1428031,104975.0,2018-12-06 15:23:43,"116.28,39.80","116.33,39.90",2018-12-06 15:23:43,"[{""distance"": 22596, ""price"": 600, ""eta"": 8587...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94334,1437258,203066.0,2018-12-06 20:45:58,"116.35,39.84","116.33,39.89",2018-12-06 20:45:58,"[{""distance"": 10916, ""price"": 400, ""eta"": 2235...",0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
94335,437239,112948.0,2018-12-01 23:44:19,"116.32,39.64","116.27,40.09",NaN,NaN,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94336,1255824,187471.0,2018-12-02 14:03:35,"116.63,40.05","116.51,39.92",2018-12-02 14:03:35,"[{""distance"": 35486, ""price"": 800, ""eta"": 6416...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94337,2037790,121018.0,2018-12-07 17:13:32,"116.40,39.95","116.40,39.95",2018-12-07 17:13:32,"[{""distance"": 362, ""price"": """", ""eta"": 308, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94338,430543,180567.0,2018-12-01 09:38:27,"116.42,39.73","116.40,39.76",2018-12-01 09:38:27,"[{""distance"": 5634, ""price"": 1400, ""eta"": 1018...",0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
94339,1438109,103961.0,2018-12-06 18:49:53,"116.43,39.94","116.37,39.86",2018-12-06 18:49:53,"[{""distance"": 14088, ""price"": 500, ""eta"": 2236...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94340,1400878,166754.0,2018-12-03 22:58:01,"116.56,39.79","116.49,39.79",2018-12-03 22:58:01,"[{""distance"": 8426, ""price"": 3300, ""eta"": 1574...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94341,1410511,207359.0,2018-12-06 22:12:18,"116.37,39.98","116.86,40.37",2018-12-06 22:12:18,"[{""distance"": 79407, ""price"": """", ""eta"": 3761,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94342,2046228,133934.0,2018-12-07 19:24:13,"116.32,39.89","116.60,40.08",NaN,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94343,1123391,192931.0,2018-12-05 12:56:04,"116.56,40.22","116.42,39.90",2018-12-05 12:56:04,"[{""distance"": 55332, ""price"": 1100, ""eta"": 884...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94344,1334930,153397.0,2018-12-04 22:01:58,"116.63,40.12","116.65,40.12",2018-12-04 22:01:58,"[{""distance"": 3790, ""price"": 1400, ""eta"": 644,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94345,2053193,161567.0,2018-12-07 21:52:24,"116.27,39.91","116.34,39.92",2018-12-07 21:52:24,"[{""distance"": 9610, ""price"": 600, ""eta"": 2587,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94346,1143957,170839.0,2018-12-05 11:07:25,"116.45,39.91","116.34,39.91",2018-12-05 11:07:25,"[{""distance"": 11179, ""price"": 400, ""eta"": 2017...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94347,1361900,102295.0,2018-12-04 10:29:46,"116.39,39.95","116.36,39.92",2018-12-04 10:29:46,"[{""distance"": 7049, ""price"": 300, ""eta"": 2081,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94348,459896,204610.0,2018-12-01 08:26:25,"116.44,39.92","116.41,39.95",2018-12-01 08:26:25,"[{""distance"": 6924, ""price"": 300, ""eta"": 2051,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94349,1344076,106860.0,2018-12-04 15:30:11,"116.39,39.79","116.61,39.92",2018-12-04 15:30:11,"[{""distance"": 36216, ""price"": 800, ""eta"": 5791...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94350,1329537,153660.0,2018-12-04 12:55:39,"116.76,39.75","116.50,39.84",2018-12-04 12:55:39,"[{""distance"": 52044, ""price"": 1300, ""eta"": 979...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94351,1393464,113473.0,2018-12-03 18:58:58,"116.63,40.30","116.63,40.30",2018-12-03 18:58:58,"[{""distance"": 608, ""price"": """", ""eta"": 519, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94352,1342497,151896.0,2018-12-04 15:29:38,"116.40,39.98","116.39,39.78",2018-12-04 15:29:38,"[{""distance"": 33164, ""price"": 800, ""eta"": 5578...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94353,1337980,105821.0,2018-12-04 10:40:45,"116.28,39.92","116.42,39.96",2018-12-04 10:40:45,"[{""distance"": 19272, ""price"": 700, ""eta"": 4459...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94354,1448860,171910.0,2018-12-06 11:54:12,"116.36,40.06","116.24,40.05",2018-12-06 11:54:12,"[{""distance"": 14437, ""price"": 600, ""eta"": 5536...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94355,1253699,209130.0,2018-12-02 15:31:17,"116.23,40.18","116.23,40.22",2018-12-02 15:31:17,"[{""distance"": 5486, ""price"": 200, ""eta"": 1884,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94356,1273922,143335.0,2018-12-02 07:48:52,"116.38,39.95","116.59,40.08",2018-12-02 07:48:52,"[{""distance"": 34070, ""price"": 2800, ""eta"": 402...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94357,1338573,206991.0,2018-12-04 04:39:31,"116.42,39.90","116.37,39.90",NaN,NaN,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
no_plan = test_merges.plans.values

In [5]:
#pick out which sid ddin't have plan
no_plan_index = []
for i in range(len(no_plan)):
    no_plan[i] = str(no_plan[i])
for i in range(len(no_plan)):
    if(no_plan[i] == 'nan'):
        no_plan_index.append(i)

In [6]:
len(no_plan_index)

1787

In [7]:
#use the no plan index to form the pandas
test_no_plan = test_merges.loc[no_plan_index,:]
test_no_plan

,sid,pid,req_time,o,d,plan_time,plans,p0,p1,p2,...,p56,p57,p58,p59,p60,p61,p62,p63,p64,p65
107,1109845,0.0,2018-12-05 21:56:34,"116.39,39.78","116.37,39.86",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109,2043193,0.0,2018-12-07 11:04:45,"116.41,39.86","116.39,39.78",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
113,2067285,0.0,2018-12-07 11:28:55,"116.29,39.91","116.37,39.93",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
212,1263692,0.0,2018-12-02 19:31:54,"116.37,39.86","116.59,40.08",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
254,1141190,0.0,2018-12-05 15:04:22,"116.43,39.94","116.34,39.93",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
528,1344396,0.0,2018-12-04 13:11:30,"116.43,39.92","116.37,39.91",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
539,1130573,0.0,2018-12-05 10:58:53,"116.37,39.86","116.37,39.94",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
566,459267,0.0,2018-12-01 02:20:36,"116.59,40.08","116.54,39.90",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
584,1274977,0.0,2018-12-02 08:40:52,"116.50,39.86","116.50,39.86",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
611,1109837,0.0,2018-12-05 23:56:31,"116.39,39.78","116.37,39.86",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
613,467774,0.0,2018-12-01 20:42:28,"116.39,39.78","116.29,39.97",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
614,2059899,0.0,2018-12-07 22:37:55,"116.68,39.93","116.61,40.05",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
659,2059752,0.0,2018-12-07 17:11:00,"116.45,39.90","116.64,40.13",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
666,1117277,0.0,2018-12-05 14:19:16,"116.37,39.86","116.37,39.93",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
745,2038995,0.0,2018-12-07 01:02:34,"116.39,39.78","116.37,39.86",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
795,1397613,0.0,2018-12-03 22:37:00,"116.32,39.89","116.44,39.87",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
825,1260661,0.0,2018-12-02 07:54:19,"116.26,40.22","116.24,40.21",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
826,1271091,0.0,2018-12-02 21:20:34,"116.28,40.01","116.40,39.94",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
865,1253690,0.0,2018-12-02 09:05:36,"116.37,39.86","116.55,40.06",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
897,1357035,0.0,2018-12-04 16:48:53,"116.81,40.16","116.13,39.71",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
937,1348981,0.0,2018-12-04 20:07:56,"116.39,39.86","116.37,39.92",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1005,1388021,0.0,2018-12-03 09:10:56,"116.39,39.79","116.32,39.89",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1137,1348564,0.0,2018-12-04 20:23:24,"116.41,39.90","116.19,39.94",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1160,2049957,0.0,2018-12-07 13:03:30,"116.63,39.94","116.39,39.91",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1180,1351268,0.0,2018-12-04 10:19:41,"116.32,39.89","116.42,39.90",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1212,1331526,0.0,2018-12-04 16:11:35,"116.39,39.78","116.37,39.86",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1233,424384,0.0,2018-12-01 15:37:21,"116.39,39.78","116.37,39.86",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1307,1145329,0.0,2018-12-05 14:17:53,"116.33,40.00","116.37,39.87",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1349,1331620,0.0,2018-12-04 14:35:47,"116.39,39.78","116.37,39.86",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1385,1355716,0.0,2018-12-04 00:35:11,"116.61,40.05","116.50,40.08",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93762,2056722,164047.0,2018-12-07 13:35:23,"116.28,40.07","116.53,39.80",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
93790,2075038,206966.0,2018-12-07 12:03:39,"116.44,39.96","116.36,39.89",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
93799,1280610,121749.0,2018-12-02 11:21:22,"116.59,40.08","116.42,39.90",NaN,nan,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
93803,2045497,102753.0,2018-12-07 22:07:26,"116.42,39.90","116.42,39.80",NaN,nan,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
93862,1251805,111581.0,2018-12-02 22:20:56,"116.42,39.90","116.41,39.96",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
93884,1275930,103887.0,2018-12-02 20:16:42,"116.42,39.90","116.40,39.97",NaN,nan,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
93894,1112914,108584.0,2018-12-05 10:16:55,"116.56,40.07","116.46,39.98",NaN,nan,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
93904,425896,144124.0,2018-12-01 06:55:00,"116.32,39.95","116.42,39.94",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
93913,1112855,193577.0,2018-12-05 21:52:50,"116.61,40.05","116.43,39.93",NaN,nan,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
93917,2054605,146465.0,2018-12-07 22:36:24,"116.31,39.95","116.43,39.99",NaN,nan,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
93929,1144059,183861.0,2018-12-05 22:59:28,"116.39,39.79","116.59,40.08",NaN,nan,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
93945,1139315,190263.0,2018-12-05 20:30:30,"116.42,39.90","116.32,39.89",NaN,nan,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
93952,1122163,102354.0,2018-12-05 01:11:26,"116.40,40.10","116.65,39.89",NaN,nan,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
93988,457077,183852.0,2018-12-01 13:35:35,"116.47,39.91","116.45,39.89",NaN,nan,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
94001,1132970,166520.0,2018-12-05 17:17:53,"116.32,39.89","116.33,39.73",NaN,nan,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94005,1251766,145106.0,2018-12-02 00:07:09,"116.32,39.89","116.58,40.08",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94023,1383289,149504.0,2018-12-03 11:18:17,"116.12,40.07","116.32,39.89",NaN,nan,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94039,1272566,184447.0,2018-12-02 18:32:39,"116.51,39.93","116.26,39.87",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94072,1132006,178535.0,2018-12-05 20:33:34,"116.37,39.85","116.39,39.88",NaN,nan,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94086,1110273,210137.0,2018-12-05 22:15:09,"116.40,39.99","116.37,40.00",NaN,nan,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94099,2056356,119134.0,2018-12-07 10:36:52,"116.42,39.90","116.44,39.91",NaN,nan,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94106,465656,169873.0,2018-12-01 10:55:19,"116.36,39.99","116.31,39.99",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94156,1424066,209252.0,2018-12-06 07:57:58,"116.33,39.73","116.55,39.75",NaN,nan,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
94159,1442927,122889.0,2018-12-06 23:38:45,"116.28,39.79","116.27,39.91",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94172,2065685,109227.0,2018-12-07 07:31:54,"116.48,39.84","116.64,39.89",NaN,nan,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94285,1396079,205174.0,2018-12-03 07:40:40,"116.53,39.82","116.45,39.83",NaN,nan,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94315,1413346,120568.0,2018-12-06 04:53:34,"116.32,39.90","116.49,39.62",NaN,nan,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94335,437239,112948.0,2018-12-01 23:44:19,"116.32,39.64","116.27,40.09",NaN,nan,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94342,2046228,133934.0,2018-12-07 19:24:13,"116.32,39.89","116.60,40.08",NaN,nan,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94357,1338573,206991.0,2018-12-04 04:39:31,"116.42,39.90","116.37,39.90",NaN,nan,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
#because no plan so give recommend_mode: 0 to the sid
no_plan_sid = test_no_plan.sid

no_plan_data = pd.DataFrame({'sid':no_plan_sid})
no_plan_data['recommend_mode'] = '0'
no_plan_data

           sid recommend_mode
107    1109845              0
109    2043193              0
113    2067285              0
212    1263692              0
254    1141190              0
528    1344396              0
539    1130573              0
566     459267              0
584    1274977              0
611    1109837              0
613     467774              0
614    2059899              0
659    2059752              0
666    1117277              0
745    2038995              0
795    1397613              0
825    1260661              0
826    1271091              0
865    1253690              0
897    1357035              0
937    1348981              0
1005   1388021              0
1137   1348564              0
1160   2049957              0
1180   1351268              0
1212   1331526              0
1233    424384              0
1307   1145329              0
1349   1331620              0
1385   1355716              0
...        ...            ...
93762  2056722              0
93790  2075038              0
93799  1280610              0
93803  2045497              0
93862  1251805              0
93884  1275930              0
93894  1112914              0
93904   425896              0
93913  1112855              0
93917  2054605              0
93929  1144059              0
93945  1139315              0
93952  1122163              0
93988   457077              0
94001  1132970              0
94005  1251766              0
94023  1383289              0
94039  1272566              0
94072  1132006              0
94086  1110273              0
94099  2056356              0
94106   465656              0
94156  1424066              0
94159  1442927              0
94172  2065685              0
94285  1396079              0
94315  1413346              0
94335   437239              0
94342  2046228              0
94357  1338573              0

[1787 rows x 2 columns]

In [9]:
#drop no plan data
test_merges = test_merges.drop(index = no_plan_index)
test_merges

,sid,pid,req_time,o,d,plan_time,plans,p0,p1,p2,...,p56,p57,p58,p59,p60,p61,p62,p63,p64,p65
0,1126541,178395.0,2018-12-05 14:51:43,"116.41,39.92","116.46,39.95",2018-12-05 14:51:43,"[{""distance"": 13610, ""price"": 400, ""eta"": 2388...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1389752,178395.0,2018-12-03 17:30:22,"116.40,39.91","116.46,39.95",2018-12-03 17:30:22,"[{""distance"": 10499, ""price"": 400, ""eta"": 2946...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1126543,178395.0,2018-12-05 12:10:43,"116.41,39.92","116.32,39.89",2018-12-05 12:10:43,"[{""distance"": 12277, ""price"": 400, ""eta"": 2319...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,1349248,178395.0,2018-12-04 09:42:37,"116.41,39.91","116.46,39.95",2018-12-04 09:42:37,"[{""distance"": 9710, ""price"": 400, ""eta"": 2270,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1349239,178395.0,2018-12-04 22:49:10,"116.32,39.89","116.41,39.92",2018-12-04 22:49:10,"[{""distance"": 10475, ""price"": 4000, ""eta"": 194...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5,1349241,178395.0,2018-12-04 09:34:17,"116.41,39.91","116.30,39.92",2018-12-04 09:34:17,"[{""distance"": 12438, ""price"": 400, ""eta"": 2247...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
6,1126542,178395.0,2018-12-05 12:08:39,"116.41,39.92","116.46,39.95",2018-12-05 12:08:39,"[{""distance"": 13758, ""price"": 400, ""eta"": 2519...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
7,1349243,178395.0,2018-12-04 09:13:49,"116.41,39.91","116.30,39.92",2018-12-04 09:13:49,"[{""distance"": 12738, ""price"": 1800, ""eta"": 257...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
8,1349244,178395.0,2018-12-04 10:05:37,"116.31,39.91","116.29,39.92",2018-12-04 10:05:37,"[{""distance"": 3245, ""price"": 300, ""eta"": 1137,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9,1126540,178395.0,2018-12-05 15:24:34,"116.46,39.95","116.46,39.95",2018-12-05 15:24:34,"[{""distance"": 458, ""price"": """", ""eta"": 391, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10,1349240,178395.0,2018-12-04 08:51:50,"116.41,39.92","116.29,39.92",2018-12-04 08:51:50,"[{""distance"": 13856, ""price"": 500, ""eta"": 2860...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
11,453685,179178.0,2018-12-01 12:50:33,"116.39,39.90","116.41,39.91",2018-12-01 12:50:33,"[{""distance"": 2858, ""price"": 200, ""eta"": 1798,...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
12,1107620,179178.0,2018-12-05 13:11:30,"116.57,39.91","116.48,39.88",2018-12-05 13:11:30,"[{""distance"": 12615, ""price"": 400, ""eta"": 2650...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
13,1107621,179178.0,2018-12-05 17:37:08,"116.47,39.89","116.31,39.67",2018-12-05 17:37:08,"[{""distance"": 37332, ""price"": 700, ""eta"": 3962...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14,1107618,179178.0,2018-12-05 13:14:29,"116.57,39.91","116.48,39.88",2018-12-05 13:14:29,"[{""distance"": 12583, ""price"": 400, ""eta"": 2621...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
15,1349032,179178.0,2018-12-04 22:12:58,"116.30,39.62","116.29,39.87",2018-12-04 22:12:58,"[{""distance"": 34150, ""price"": """", ""eta"": 2078,...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
16,1437724,179178.0,2018-12-06 14:29:56,"116.40,39.97","116.41,39.96",2018-12-06 14:29:56,"[{""distance"": 1348, ""price"": """", ""eta"": 1171, ...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
17,2066073,184748.0,2018-12-07 10:17:35,"116.37,39.71","116.31,39.89",2018-12-07 10:17:35,"[{""distance"": 33453, ""price"": 800, ""eta"": 5624...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,452746,162795.0,2018-12-01 07:52:44,"116.33,39.97","116.31,39.98",2018-12-01 07:52:44,"[{""distance"": 4007, ""price"": 1500, ""eta"": 989,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19,452745,162795.0,2018-12-01 07:57:29,"116.32,39.96","116.31,39.98",2018-12-01 07:57:29,"[{""distance"": 2650, ""price"": 300, ""eta"": 961, ...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
20,1431672,116384.0,2018-12-06 10:36:30,"116.51,39.68","116.51,39.68",2018-12-06 10:36:30,"[{""distance"": 692, ""price"": """", ""eta"": 591, ""t...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
21,2060796,116384.0,2018-12-07 15:57:48,"116.42,39.82","116.42,39.82",2018-12-07 15:57:48,"[{""distance"": 864, ""price"": """", ""eta"": 740, ""t...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
22,2060799,116384.0,2018-12-07 14:51:03,"116.41,39.91","116.41,39.84",2018-12-07 14:51:03,"[{""distance"": 10487, ""price"": 400, ""eta"": 1994...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
23,1431678,116384.0,2018-12-06 09:09:51,"116.44,39.84","116.51,39.68",2018-12-06 09:09:51,"[{""distance"": 24286, ""price"": 2900, ""eta"": 517...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
24,2060795,116384.0,2018-12-07 08:46:50,"116.65,40.13","116.31,39.98",2018-12-07 08:46:50,"[{""distance"": 43240, ""price"": 700, ""eta"": 5135...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
25,1431680,116384.0,2018-12-06 07:55:19,"116.43,39.85","116.31,39.98",2018-12-06 07:55:19,"[{""distance"": 27894, ""price"": 600, ""eta"": 4549...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
26,2060792,116384.0,2018-12-07 15:44:03,"116.42,39.84","116.42,39.82",2018-12-07 15:44:03,"[{""distance"": 4413, ""price"": 200, ""eta"": 1840,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
27,2060797,116384.0,2018-12-07 09:37:00,"116.40,40.00","116.31,39.97",2018-12-07 09:37:00,"[{""distance"": 11058, ""price"": 400, ""eta"": 2134...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
28,1128839,116384.0,2018-12-05 22:42:57,"116.59,40.08","116.51,39.68",2018-12-05 22:42:57,"[{""distance"": 60445, ""price"": """", ""eta"": 3998,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
29,1128838,116384.0,2018-12-05 22:43:20,"116.59,40.08","116.51,39.68",2018-12-05 22:43:20,"[{""distance"": 60445, ""price"": """", ""eta"": 4000,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94325,1419477,128755.0,2018-12-06 08:55:25,"116.29,39.95","116.44,39.96",2018-12-06 08:55:25,"[{""distance"": 19825, ""price"": 500, ""eta"": 3113...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94326,1413463,148040.0,2018-12-06 21:59:42,"116.49,39.93","116.34,39.90",2018-12-06 21:59:42,"[{""distance"": 17660, ""price"": 700, ""eta"": 4541...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94327,1123701,133261.0,2018-12-05 09:43:10,"116.42,40.07","116.49,40.14",2018-12-05 09:43:10,"[{""distance"": 12349, ""price"": 400, ""eta"": 3723...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94328,1393550,176518.0,2018-12-03 19:27:37,"116.39,39.98","116.40,39.93",2018-12-03 19:27:37,"[{""distance"": 7038, ""price"": 400, ""eta"": 1402,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
94329,1415669,216654.0,2018-12-06 12:06:45,"116.64,40.34","116.59,40.92",2018-12-06 12:06:45,"[{""distance"": 87930, ""price"": """", ""eta"": 5486,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94330,1108383,103104.0,2018-12-05 21:53:43,"116.46,39.94","116.47,39.93",2018-12-05 21:53:43,"[{""distance"": 2449, ""price"": 200, ""eta"": 1807,...",0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
94331,1279336,161440.0,2018-12-02 09:05:42,"116.34,39.71","116.42,39.90",2018-12-02 09:05:42,"[{""distance"": 30671, ""price"": 800, ""eta"": 5450...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94332,1423005,188097.0,2018-12-06 14:24:31,"116.40,40.00","116.32,39.89",2018-12-06 14:24:31,"[{""distance"": 23618, ""price"": 500, ""eta"": 4315...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94333,1428031,104975.0,2018-12-06 15:23:43,"116.28,39.80","116.33,39.90",2018-12-06 15:23:43,"[{""distance"": 22596, ""price"": 600, ""eta"": 8587...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94334,1437258,203066.0,2018-12-06 20:45:58,"116.35,39.84","116.33,39.89",2018-12-06 20:45:58,"[{""distance"": 10916, ""price"": 400, ""eta"": 2235...",0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
94336,1255824,187471.0,2018-12-02 14:03:35,"116.63,40.05","116.51,39.92",2018-12-02 14:03:35,"[{""distance"": 35486, ""price"": 800, ""eta"": 6416...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94337,2037790,121018.0,2018-12-07 17:13:32,"116.40,39.95","116.40,39.95",2018-12-07 17:13:32,"[{""distance"": 362, ""price"": """", ""eta"": 308, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94338,430543,180567.0,2018-12-01 09:38:27,"116.42,39.73","116.40,39.76",2018-12-01 09:38:27,"[{""distance"": 5634, ""price"": 1400, ""eta"": 1018...",0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
94339,1438109,103961.0,2018-12-06 18:49:53,"116.43,39.94","116.37,39.86",2018-12-06 18:49:53,"[{""distance"": 14088, ""price"": 500, ""eta"": 2236...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94340,1400878,166754.0,2018-12-03 22:58:01,"116.56,39.79","116.49,39.79",2018-12-03 22:58:01,"[{""distance"": 8426, ""price"": 3300, ""eta"": 1574...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94341,1410511,207359.0,2018-12-06 22:12:18,"116.37,39.98","116.86,40.37",2018-12-06 22:12:18,"[{""distance"": 79407, ""price"": """", ""eta"": 3761,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94343,1123391,192931.0,2018-12-05 12:56:04,"116.56,40.22","116.42,39.90",2018-12-05 12:56:04,"[{""distance"": 55332, ""price"": 1100, ""eta"": 884...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94344,1334930,153397.0,2018-12-04 22:01:58,"116.63,40.12","116.65,40.12",2018-12-04 22:01:58,"[{""distance"": 3790, ""price"": 1400, ""eta"": 644,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94345,2053193,161567.0,2018-12-07 21:52:24,"116.27,39.91","116.34,39.92",2018-12-07 21:52:24,"[{""distance"": 9610, ""price"": 600, ""eta"": 2587,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94346,1143957,170839.0,2018-12-05 11:07:25,"116.45,39.91","116.34,39.91",2018-12-05 11:07:25,"[{""distance"": 11179, ""price"": 400, ""eta"": 2017...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94347,1361900,102295.0,2018-12-04 10:29:46,"116.39,39.95","116.36,39.92",2018-12-04 10:29:46,"[{""distance"": 7049, ""price"": 300, ""eta"": 2081,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94348,459896,204610.0,2018-12-01 08:26:25,"116.44,39.92","116.41,39.95",2018-12-01 08:26:25,"[{""distance"": 6924, ""price"": 300, ""eta"": 2051,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94349,1344076,106860.0,2018-12-04 15:30:11,"116.39,39.79","116.61,39.92",2018-12-04 15:30:11,"[{""distance"": 36216, ""price"": 800, ""eta"": 5791...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94350,1329537,153660.0,2018-12-04 12:55:39,"116.76,39.75","116.50,39.84",2018-12-04 12:55:39,"[{""distance"": 52044, ""price"": 1300, ""eta"": 979...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94351,1393464,113473.0,2018-12-03 18:58:58,"116.63,40.30","116.63,40.30",2018-12-03 18:58:58,"[{""distance"": 608, ""price"": """", ""eta"": 519, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94352,1342497,151896.0,2018-12-04 15:29:38,"116.40,39.98","116.39,39.78",2018-12-04 15:29:38,"[{""distance"": 33164, ""price"": 800, ""eta"": 5578...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94353,1337980,105821.0,2018-12-04 10:40:45,"116.28,39.92","116.42,39.96",2018-12-04 10:40:45,"[{""distance"": 19272, ""price"": 700, ""eta"": 4459...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94354,1448860,171910.0,2018-12-06 11:54:12,"116.36,40.06","116.24,40.05",2018-12-06 11:54:12,"[{""distance"": 14437, ""price"": 600, ""eta"": 5536...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94355,1253699,209130.0,2018-12-02 15:31:17,"116.23,40.18","116.23,40.22",2018-12-02 15:31:17,"[{""distance"": 5486, ""price"": 200, ""eta"": 1884,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94356,1273922,143335.0,2018-12-02 07:48:52,"116.38,39.95","116.59,40.08",2018-12-02 07:48:52,"[{""distance"": 34070, ""price"": 2800, ""eta"": 402...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [10]:
#start to deal with no_pid and gove the data the most recommend_mode
no_pid = test_merges.pid.values
#先把index加入array 之後把沒有pid的那個index加入no_pid_index 以便之後drop
pid_index = test_merges.index.values
len(no_pid)

array([94336, 94337, 94338, 94339, 94340, 94341, 94343, 94344, 94345,
       94346, 94347, 94348, 94349, 94350, 94351, 94352, 94353, 94354,
       94355])

In [11]:
#pick out which sid ddin't have pid
no_pid_index = []
for i in range(len(no_pid)):
    if(no_pid[i] == 0):
        no_pid_index.append(pid_index[i])

In [12]:
len(no_pid_index)

30813

In [13]:
#use the no pid index to form the pandas
test_no_pid = test_merges.loc[no_pid_index,:]
test_no_pid

,sid,pid,req_time,o,d,plan_time,plans,p0,p1,p2,...,p56,p57,p58,p59,p60,p61,p62,p63,p64,p65
68,1404698,0.0,2018-12-03 15:02:30,"116.37,39.93","116.32,39.79",2018-12-03 15:02:30,"[{""distance"": 18454, ""price"": 500, ""eta"": 2388...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
69,1344781,0.0,2018-12-04 11:26:53,"116.35,39.91","116.37,39.96",2018-12-04 11:26:53,"[{""distance"": 7439, ""price"": 200, ""eta"": 3149,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70,2081060,0.0,2018-12-07 17:56:46,"116.28,40.01","116.30,39.87",2018-12-07 17:56:46,"[{""distance"": 19706, ""price"": 900, ""eta"": 4563...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71,1387645,0.0,2018-12-03 12:42:52,"116.43,39.94","116.41,39.73",2018-12-03 12:42:52,"[{""distance"": 38545, ""price"": 800, ""eta"": 6034...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
72,1413992,0.0,2018-12-06 19:06:59,"116.38,39.97","116.58,40.08",2018-12-06 19:06:59,"[{""distance"": 26622, ""price"": 2200, ""eta"": 504...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73,1107041,0.0,2018-12-05 18:40:11,"116.60,39.91","116.61,39.88",2018-12-05 18:40:11,"[{""distance"": 6570, ""price"": 200, ""eta"": 2521,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
74,1130965,0.0,2018-12-05 07:44:27,"116.47,39.87","116.43,39.86",2018-12-05 07:44:27,"[{""distance"": 5356, ""price"": """", ""eta"": 1111, ...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75,1277353,0.0,2018-12-02 22:47:22,"116.21,39.97","116.34,40.04",2018-12-02 22:47:22,"[{""distance"": 22011, ""price"": """", ""eta"": 1429,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76,1112972,0.0,2018-12-05 11:28:26,"116.43,39.91","116.43,39.92",2018-12-05 11:28:26,"[{""distance"": 759, ""price"": """", ""eta"": 668, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
77,2040880,0.0,2018-12-07 19:48:34,"116.34,39.87","116.40,39.92",2018-12-07 19:48:34,"[{""distance"": 12514, ""price"": 600, ""eta"": 4452...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78,1260071,0.0,2018-12-02 10:58:02,"116.35,39.97","116.35,39.99",2018-12-02 10:58:02,"[{""distance"": 2169, ""price"": 200, ""eta"": 870, ...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79,1253643,0.0,2018-12-02 02:39:32,"116.31,39.76","116.59,39.90",2018-12-02 02:39:32,"[{""distance"": 40601, ""price"": """", ""eta"": 2552,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
80,1134866,0.0,2018-12-05 19:45:37,"116.36,39.98","116.41,39.91",2018-12-05 19:45:37,"[{""distance"": 19216, ""price"": 500, ""eta"": 2724...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
81,1276460,0.0,2018-12-02 16:56:40,"116.33,40.08","116.33,40.07",2018-12-02 16:56:40,"[{""distance"": 885, ""price"": """", ""eta"": 807, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
82,462855,0.0,2018-12-01 08:49:13,"116.46,39.90","116.46,39.92",2018-12-01 08:49:13,"[{""distance"": 3213, ""price"": 1300, ""eta"": 769,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83,1145291,0.0,2018-12-05 19:49:43,"116.31,39.84","116.31,40.07",2018-12-05 19:49:43,"[{""distance"": 34694, ""price"": 600, ""eta"": 3950...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84,1351985,0.0,2018-12-04 16:06:56,"116.40,39.97","116.33,40.05",2018-12-04 16:06:56,"[{""distance"": 14432, ""price"": 400, ""eta"": 4469...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85,1365883,0.0,2018-12-04 17:55:20,"116.46,39.93","116.46,39.93",2018-12-04 17:55:20,"[{""distance"": 311, ""price"": """", ""eta"": 284, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86,1114417,0.0,2018-12-05 18:23:20,"116.28,39.93","116.29,39.94",2018-12-05 18:23:20,"[{""distance"": 3744, ""price"": 300, ""eta"": 1988,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87,1260565,0.0,2018-12-02 09:40:28,"116.35,39.98","116.32,39.89",2018-12-02 09:40:28,"[{""distance"": 15997, ""price"": 700, ""eta"": 3744...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
88,1399483,0.0,2018-12-03 11:59:48,"116.35,40.04","116.39,39.89",2018-12-03 11:59:48,"[{""distance"": 24189, ""price"": 600, ""eta"": 4063...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
89,2049462,0.0,2018-12-07 15:56:20,"116.48,39.91","116.43,39.99",2018-12-07 15:56:20,"[{""distance"": 14068, ""price"": 300, ""eta"": 4316...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
90,1373191,0.0,2018-12-03 23:37:57,"116.40,40.05","116.61,40.07",2018-12-03 23:37:57,"[{""distance"": 28724, ""price"": """", ""eta"": 2617,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
91,1394860,0.0,2018-12-03 08:04:38,"116.43,39.98","116.32,39.89",2018-12-03 08:04:38,"[{""distance"": 19873, ""price"": 500, ""eta"": 3090...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
92,457460,0.0,2018-12-01 21:07:27,"116.46,40.01","116.42,40.05",2018-12-01 21:07:27,"[{""distance"": 11837, ""price"": 400, ""eta"": 2991...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93,1130488,0.0,2018-12-05 11:13:26,"116.43,39.92","116.31,39.88",2018-12-05 11:13:26,"[{""distance"": 17161, ""price"": 600, ""eta"": 3402...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94,1329416,0.0,2018-12-04 19:05:19,"116.40,39.95","116.40,39.95",2018-12-04 19:05:19,"[{""distance"": 399, ""price"": """", ""eta"": 341, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
95,440945,0.0,2018-12-01 18:23:47,"116.50,39.92","116.50,39.92",2018-12-01 18:23:47,"[{""distance"": 252, ""price"": """", ""eta"": 214, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,442708,0.0,2018-12-01 07:52:02,"116.42,39.98","116.27,40.10",2018-12-01 07:52:02,"[{""distance"": 31846, ""price"": 800, ""eta"": 5060...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,2066470,0.0,2018-12-07 09:40:59,"116.40,40.06","116.48,39.91",2018-12-07 09:40:59,"[{""distance"": 23735, ""price"": 500, ""eta"": 4822...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31483,1143756,0.0,2018-12-05 14:03:20,"116.31,39.89","116.36,39.95",2018-12-05 14:03:20,"[{""distance"": 11900, ""price"": 400, ""eta"": 2952...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31484,1125253,0.0,2018-12-05 11:55:42,"116.46,39.95","116.42,40.04",2018-12-05 11:55:42,"[{""distance"": 15061, ""price"": 500, ""eta"": 3094...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31485,427277,0.0,2018-12-01 11:17:12,"116.21,39.91","116.30,39.88",2018-12-01 11:17:12,"[{""distance"": 11989, ""price"": 400, ""eta"": 1769...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31486,1366993,0.0,2018-12-04 22:15:54,"116.64,39.89","116.64,39.89",2018-12-04 22:15:54,"[{""distance"": 598, ""price"": """", ""eta"": 541, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31487,1336034,0.0,2018-12-04 18:31:31,"116.45,40.00","116.48,39.97",2018-12-04 18:31:31,"[{""distance"": 5406, ""price"": 300, ""eta"": 1913,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31489,1131241,0.0,2018-12-05 13:39:31,"116.56,40.05","116.59,40.05",2018-12-05 13:39:31,"[{""distance"": 10340, ""price"": 400, ""eta"": 3590...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31490,1244118,0.0,2018-12-02 15:36:08,"116.33,40.07","116.31,40.07",2018-12-02 15:36:08,"[{""distance"": 1556, ""price"": 300, ""eta"": 481, ...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31491,427653,0.0,2018-12-01 21:30:58,"116.51,39.91","116.57,39.87",2018-12-01 21:30:58,"[{""distance"": 11484, ""price"": 300, ""eta"": 2679...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31492,1335020,0.0,2018-12-04 22:15:15,"116.34,39.94","116.43,39.90",2018-12-04 22:15:17,"[{""distance"": 13513, ""price"": 400, ""eta"": 3060...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31493,427282,0.0,2018-12-01 15:57:27,"116.27,39.91","116.20,39.95",2018-12-01 15:57:27,"[{""distance"": 12805, ""price"": 500, ""eta"": 4057...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31494,1249644,0.0,2018-12-02 11:50:32,"116.42,39.86","116.36,39.95",2018-12-02 11:50:32,"[{""distance"": 15327, ""price"": 500, ""eta"": 3188...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31495,1444617,0.0,2018-12-06 09:16:29,"116.40,39.89","116.42,39.96",2018-12-06 09:16:29,"[{""distance"": 10595, ""price"": 400, ""eta"": 3273...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31496,1359775,0.0,2018-12-04 17:18:03,"116.30,40.05","116.51,39.92",2018-12-04 17:18:03,"[{""distance"": 36355, ""price"": 600, ""eta"": 4394...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31497,1121217,0.0,2018-12-05 11:18:34,"116.48,39.98","116.49,39.97",2018-12-05 11:18:34,"[{""distance"": 4633, ""price"": 1600, ""eta"": 1177...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31498,1341947,0.0,2018-12-04 18:55:20,"116.34,40.00","116.33,40.01",2018-12-04 18:55:20,"[{""distance"": 2414, ""price"": 300, ""eta"": 1323,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31499,1438839,0.0,2018-12-06 10:56:58,"116.46,39.95","116.46,39.95",2018-12-06 10:56:58,"[{""distance"": 720, ""price"": """", ""eta"": 665, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31500,1383602,0.0,2018-12-03 11:55:26,"116.47,39.91","116.49,39.93",2018-12-03 11:55:26,"[{""distance"": 4939, ""price"": 200, ""eta"": 2251,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31501,1400423,0.0,2018-12-03 13:14:29,"116.30,40.05","116.43,39.76",2018-12-03 13:14:29,"[{""distance"": 55137, ""price"": 1000, ""eta"": 815...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31502,1391560,0.0,2018-12-03 17:25:14,"116.34,39.89","116.28,39.92",2018-12-03 17:25:14,"[{""distance"": 10975, ""price"": """", ""eta"": 1572,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31504,459408,0.0,2018-12-01 10:25:44,"116.10,39.90","116.37,39.86",2018-12-01 10:25:44,"[{""distance"": 29535, ""price"": 900, ""eta"": 5327...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31505,425789,0.0,2018-12-01 16:57:56,"116.46,39.97","116.46,39.98",2018-12-01 16:57:56,"[{""distance"": 1406, ""price"": """", ""eta"": 1202, ...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31506,430234,0.0,2018-12-01 17:12:40,"116.29,39.88","116.30,39.88",2018-12-01 17:12:40,"[{""distance"": 612, ""price"": """", ""eta"": 543, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31507,1268545,0.0,2018-12-02 16:23:59,"116.30,39.99","116.32,40.00",2018-12-02 16:23:59,"[{""distance"": 1474, ""price"": 200, ""eta"": 1045,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31508,445690,0.0,2018-12-01 16:33:55,"116.53,40.01","116.45,39.93",2018-12-01 16:33:55,"[{""distance"": 14333, ""price"": 300, ""eta"": 5567...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31509,1124242,0.0,2018-12-05 10:38:31,"116.52,40.01","116.29,39.83",2018-12-05 10:38:31,"[{""distance"": 45993, ""price"": 900, ""eta"": 7446...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31510,1389810,0.0,2018-12-03 19:37:31,"116.32,39.94","116.31,39.95",2018-12-03 19:37:31,"[{""distance"": 2366, ""price"": 200, ""eta"": 1695,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31511,471555,0.0,2018-12-01 22:32:41,"116.34,39.78","116.47,39.95",2018-12-01 22:32:41,"[{""distance"": 28555, ""price"": """", ""eta"": 2366,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31512,1123933,0.0,2018-12-05 17:44:49,"116.34,39.71","116.34,39.78",2018-12-05 17:44:49,"[{""distance"": 10469, ""price"": """", ""eta"": 2223,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31513,1338606,0.0,2018-12-04 22:34:20,"116.41,40.06","116.33,39.96",2018-12-04 22:34:20,"[{""distance"": 18235, ""price"": """", ""eta"": 2300,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31514,1353834,0.0,2018-12-04 11:31:05,"116.41,39.92","116.36,39.88",2018-12-04 11:31:05,"[{""distance"": 9836, ""price"": 600, ""eta"": 3109,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
no_pid_plan = test_no_pid.plans.values

In [15]:
#put the most recommend_mode into array
transport_mode_num = []

for i in tqdm(range(len(no_pid_plan))):
    # only need the first recommend plans.value
    change = str(no_pid_plan[i]).split('transport_mode')
    #if transport_mode is 10 or 11 so the strlength will be 2
    if(str(change[1])[4] == str(0)):
        transport_mode_num.append(str(10))
    elif(str(change[1])[4] == str(0)):
        transport_mode_num.append(str(11))
    else:
        transport_mode_num.append(str(change[1])[3])

HBox(children=(IntProgress(value=0, max=30813), HTML(value='')))

In [16]:
#make a most recommend mode for no_pid and form pandas
no_pid_sid = test_no_pid.sid
no_pid_data = pd.DataFrame({'sid':no_pid_sid , 'recommend_mode' : transport_mode_num})
no_pid_data = no_pid_data[['sid', 'recommend_mode']]
no_pid_data

           sid recommend_mode
68     1404698              2
69     1344781              1
70     2081060              7
71     1387645              7
72     1413992              1
73     1107041              1
74     1130965              3
75     1277353              3
76     1112972              5
77     2040880              7
78     1260071              1
79     1253643              3
80     1134866              2
81     1276460              5
82      462855              4
83     1145291              2
84     1351985              2
85     1365883              5
86     1114417              2
87     1260565              7
88     1399483              2
89     2049462              1
90     1373191              3
91     1394860              2
92      457460              2
93     1130488              7
94     1329416              5
95      440945              5
96      442708              7
97     2066470              2
...        ...            ...
31483  1143756              2
31484  1125253              2
31485   427277              2
31486  1366993              5
31487  1336034              2
31489  1131241              1
31490  1244118              2
31491   427653              1
31492  1335020              2
31493   427282              7
31494  1249644              2
31495  1444617              2
31496  1359775              2
31497  1121217              4
31498  1341947              2
31499  1438839              5
31500  1383602              1
31501  1400423              7
31502  1391560              3
31504   459408              7
31505   425789              5
31506   430234              5
31507  1268545              1
31508   445690              1
31509  1124242              7
31510  1389810              1
31511   471555              3
31512  1123933              3
31513  1338606              3
31514  1353834              7

[30813 rows x 2 columns]

In [17]:
#drop no pid data
test_merges = test_merges.drop(index = no_pid_index)
test_merges

,sid,pid,req_time,o,d,plan_time,plans,p0,p1,p2,...,p56,p57,p58,p59,p60,p61,p62,p63,p64,p65
0,1126541,178395.0,2018-12-05 14:51:43,"116.41,39.92","116.46,39.95",2018-12-05 14:51:43,"[{""distance"": 13610, ""price"": 400, ""eta"": 2388...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1389752,178395.0,2018-12-03 17:30:22,"116.40,39.91","116.46,39.95",2018-12-03 17:30:22,"[{""distance"": 10499, ""price"": 400, ""eta"": 2946...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1126543,178395.0,2018-12-05 12:10:43,"116.41,39.92","116.32,39.89",2018-12-05 12:10:43,"[{""distance"": 12277, ""price"": 400, ""eta"": 2319...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,1349248,178395.0,2018-12-04 09:42:37,"116.41,39.91","116.46,39.95",2018-12-04 09:42:37,"[{""distance"": 9710, ""price"": 400, ""eta"": 2270,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1349239,178395.0,2018-12-04 22:49:10,"116.32,39.89","116.41,39.92",2018-12-04 22:49:10,"[{""distance"": 10475, ""price"": 4000, ""eta"": 194...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5,1349241,178395.0,2018-12-04 09:34:17,"116.41,39.91","116.30,39.92",2018-12-04 09:34:17,"[{""distance"": 12438, ""price"": 400, ""eta"": 2247...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
6,1126542,178395.0,2018-12-05 12:08:39,"116.41,39.92","116.46,39.95",2018-12-05 12:08:39,"[{""distance"": 13758, ""price"": 400, ""eta"": 2519...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
7,1349243,178395.0,2018-12-04 09:13:49,"116.41,39.91","116.30,39.92",2018-12-04 09:13:49,"[{""distance"": 12738, ""price"": 1800, ""eta"": 257...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
8,1349244,178395.0,2018-12-04 10:05:37,"116.31,39.91","116.29,39.92",2018-12-04 10:05:37,"[{""distance"": 3245, ""price"": 300, ""eta"": 1137,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9,1126540,178395.0,2018-12-05 15:24:34,"116.46,39.95","116.46,39.95",2018-12-05 15:24:34,"[{""distance"": 458, ""price"": """", ""eta"": 391, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10,1349240,178395.0,2018-12-04 08:51:50,"116.41,39.92","116.29,39.92",2018-12-04 08:51:50,"[{""distance"": 13856, ""price"": 500, ""eta"": 2860...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
11,453685,179178.0,2018-12-01 12:50:33,"116.39,39.90","116.41,39.91",2018-12-01 12:50:33,"[{""distance"": 2858, ""price"": 200, ""eta"": 1798,...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
12,1107620,179178.0,2018-12-05 13:11:30,"116.57,39.91","116.48,39.88",2018-12-05 13:11:30,"[{""distance"": 12615, ""price"": 400, ""eta"": 2650...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
13,1107621,179178.0,2018-12-05 17:37:08,"116.47,39.89","116.31,39.67",2018-12-05 17:37:08,"[{""distance"": 37332, ""price"": 700, ""eta"": 3962...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14,1107618,179178.0,2018-12-05 13:14:29,"116.57,39.91","116.48,39.88",2018-12-05 13:14:29,"[{""distance"": 12583, ""price"": 400, ""eta"": 2621...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
15,1349032,179178.0,2018-12-04 22:12:58,"116.30,39.62","116.29,39.87",2018-12-04 22:12:58,"[{""distance"": 34150, ""price"": """", ""eta"": 2078,...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
16,1437724,179178.0,2018-12-06 14:29:56,"116.40,39.97","116.41,39.96",2018-12-06 14:29:56,"[{""distance"": 1348, ""price"": """", ""eta"": 1171, ...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
17,2066073,184748.0,2018-12-07 10:17:35,"116.37,39.71","116.31,39.89",2018-12-07 10:17:35,"[{""distance"": 33453, ""price"": 800, ""eta"": 5624...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,452746,162795.0,2018-12-01 07:52:44,"116.33,39.97","116.31,39.98",2018-12-01 07:52:44,"[{""distance"": 4007, ""price"": 1500, ""eta"": 989,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
19,452745,162795.0,2018-12-01 07:57:29,"116.32,39.96","116.31,39.98",2018-12-01 07:57:29,"[{""distance"": 2650, ""price"": 300, ""eta"": 961, ...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
20,1431672,116384.0,2018-12-06 10:36:30,"116.51,39.68","116.51,39.68",2018-12-06 10:36:30,"[{""distance"": 692, ""price"": """", ""eta"": 591, ""t...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
21,2060796,116384.0,2018-12-07 15:57:48,"116.42,39.82","116.42,39.82",2018-12-07 15:57:48,"[{""distance"": 864, ""price"": """", ""eta"": 740, ""t...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
22,2060799,116384.0,2018-12-07 14:51:03,"116.41,39.91","116.41,39.84",2018-12-07 14:51:03,"[{""distance"": 10487, ""price"": 400, ""eta"": 1994...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
23,1431678,116384.0,2018-12-06 09:09:51,"116.44,39.84","116.51,39.68",2018-12-06 09:09:51,"[{""distance"": 24286, ""price"": 2900, ""eta"": 517...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
24,2060795,116384.0,2018-12-07 08:46:50,"116.65,40.13","116.31,39.98",2018-12-07 08:46:50,"[{""distance"": 43240, ""price"": 700, ""eta"": 5135...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
25,1431680,116384.0,2018-12-06 07:55:19,"116.43,39.85","116.31,39.98",2018-12-06 07:55:19,"[{""distance"": 27894, ""price"": 600, ""eta"": 4549...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
26,2060792,116384.0,2018-12-07 15:44:03,"116.42,39.84","116.42,39.82",2018-12-07 15:44:03,"[{""distance"": 4413, ""price"": 200, ""eta"": 1840,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
27,2060797,116384.0,2018-12-07 09:37:00,"116.40,40.00","116.31,39.97",2018-12-07 09:37:00,"[{""distance"": 11058, ""price"": 400, ""eta"": 2134...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
28,1128839,116384.0,2018-12-05 22:42:57,"116.59,40.08","116.51,39.68",2018-12-05 22:42:57,"[{""distance"": 60445, ""price"": """", ""eta"": 3998,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
29,1128838,116384.0,2018-12-05 22:43:20,"116.59,40.08","116.51,39.68",2018-12-05 22:43:20,"[{""distance"": 60445, ""price"": """", ""eta"": 4000,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94325,1419477,128755.0,2018-12-06 08:55:25,"116.29,39.95","116.44,39.96",2018-12-06 08:55:25,"[{""distance"": 19825, ""price"": 500, ""eta"": 3113...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94326,1413463,148040.0,2018-12-06 21:59:42,"116.49,39.93","116.34,39.90",2018-12-06 21:59:42,"[{""distance"": 17660, ""price"": 700, ""eta"": 4541...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94327,1123701,133261.0,2018-12-05 09:43:10,"116.42,40.07","116.49,40.14",2018-12-05 09:43:10,"[{""distance"": 12349, ""price"": 400, ""eta"": 3723...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94328,1393550,176518.0,2018-12-03 19:27:37,"116.39,39.98","116.40,39.93",2018-12-03 19:27:37,"[{""distance"": 7038, ""price"": 400, ""eta"": 1402,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
94329,1415669,216654.0,2018-12-06 12:06:45,"116.64,40.34","116.59,40.92",2018-12-06 12:06:45,"[{""distance"": 87930, ""price"": """", ""eta"": 5486,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94330,1108383,103104.0,2018-12-05 21:53:43,"116.46,39.94","116.47,39.93",2018-12-05 21:53:43,"[{""distance"": 2449, ""price"": 200, ""eta"": 1807,...",0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
94331,1279336,161440.0,2018-12-02 09:05:42,"116.34,39.71","116.42,39.90",2018-12-02 09:05:42,"[{""distance"": 30671, ""price"": 800, ""eta"": 5450...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94332,1423005,188097.0,2018-12-06 14:24:31,"116.40,40.00","116.32,39.89",2018-12-06 14:24:31,"[{""distance"": 23618, ""price"": 500, ""eta"": 4315...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94333,1428031,104975.0,2018-12-06 15:23:43,"116.28,39.80","116.33,39.90",2018-12-06 15:23:43,"[{""distance"": 22596, ""price"": 600, ""eta"": 8587...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94334,1437258,203066.0,2018-12-06 20:45:58,"116.35,39.84","116.33,39.89",2018-12-06 20:45:58,"[{""distance"": 10916, ""price"": 400, ""eta"": 2235...",0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
94336,1255824,187471.0,2018-12-02 14:03:35,"116.63,40.05","116.51,39.92",2018-12-02 14:03:35,"[{""distance"": 35486, ""price"": 800, ""eta"": 6416...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94337,2037790,121018.0,2018-12-07 17:13:32,"116.40,39.95","116.40,39.95",2018-12-07 17:13:32,"[{""distance"": 362, ""price"": """", ""eta"": 308, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94338,430543,180567.0,2018-12-01 09:38:27,"116.42,39.73","116.40,39.76",2018-12-01 09:38:27,"[{""distance"": 5634, ""price"": 1400, ""eta"": 1018...",0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
94339,1438109,103961.0,2018-12-06 18:49:53,"116.43,39.94","116.37,39.86",2018-12-06 18:49:53,"[{""distance"": 14088, ""price"": 500, ""eta"": 2236...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94340,1400878,166754.0,2018-12-03 22:58:01,"116.56,39.79","116.49,39.79",2018-12-03 22:58:01,"[{""distance"": 8426, ""price"": 3300, ""eta"": 1574...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94341,1410511,207359.0,2018-12-06 22:12:18,"116.37,39.98","116.86,40.37",2018-12-06 22:12:18,"[{""distance"": 79407, ""price"": """", ""eta"": 3761,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94343,1123391,192931.0,2018-12-05 12:56:04,"116.56,40.22","116.42,39.90",2018-12-05 12:56:04,"[{""distance"": 55332, ""price"": 1100, ""eta"": 884...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94344,1334930,153397.0,2018-12-04 22:01:58,"116.63,40.12","116.65,40.12",2018-12-04 22:01:58,"[{""distance"": 3790, ""price"": 1400, ""eta"": 644,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94345,2053193,161567.0,2018-12-07 21:52:24,"116.27,39.91","116.34,39.92",2018-12-07 21:52:24,"[{""distance"": 9610, ""price"": 600, ""eta"": 2587,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94346,1143957,170839.0,2018-12-05 11:07:25,"116.45,39.91","116.34,39.91",2018-12-05 11:07:25,"[{""distance"": 11179, ""price"": 400, ""eta"": 2017...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94347,1361900,102295.0,2018-12-04 10:29:46,"116.39,39.95","116.36,39.92",2018-12-04 10:29:46,"[{""distance"": 7049, ""price"": 300, ""eta"": 2081,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94348,459896,204610.0,2018-12-01 08:26:25,"116.44,39.92","116.41,39.95",2018-12-01 08:26:25,"[{""distance"": 6924, ""price"": 300, ""eta"": 2051,...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94349,1344076,106860.0,2018-12-04 15:30:11,"116.39,39.79","116.61,39.92",2018-12-04 15:30:11,"[{""distance"": 36216, ""price"": 800, ""eta"": 5791...",1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94350,1329537,153660.0,2018-12-04 12:55:39,"116.76,39.75","116.50,39.84",2018-12-04 12:55:39,"[{""distance"": 52044, ""price"": 1300, ""eta"": 979...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94351,1393464,113473.0,2018-12-03 18:58:58,"116.63,40.30","116.63,40.30",2018-12-03 18:58:58,"[{""distance"": 608, ""price"": """", ""eta"": 519, ""t...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
94352,1342497,151896.0,2018-12-04 15:29:38,"116.40,39.98","116.39,39.78",2018-12-04 15:29:38,"[{""distance"": 33164, ""price"": 800, ""eta"": 5578...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
94353,1337980,105821.0,2018-12-04 10:40:45,"116.28,39.92","116.42,39.96",2018-12-04 10:40:45,"[{""distance"": 19272, ""price"": 700, ""eta"": 4459...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94354,1448860,171910.0,2018-12-06 11:54:12,"116.36,40.06","116.24,40.05",2018-12-06 11:54:12,"[{""distance"": 14437, ""price"": 600, ""eta"": 5536...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
94355,1253699,209130.0,2018-12-02 15:31:17,"116.23,40.18","116.23,40.22",2018-12-02 15:31:17,"[{""distance"": 5486, ""price"": 200, ""eta"": 1884,...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
94356,1273922,143335.0,2018-12-02 07:48:52,"116.38,39.95","116.59,40.08",2018-12-02 07:48:52,"[{""distance"": 34070, ""price"": 2800, ""eta"": 402...",0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [19]:
#開始處理 剩下data 先存起來 處理完再呼叫回來
# test_merges.to_csv('/storage/kdd/test_final1.csv',index = False)
#經過preprocessing(把o d time切出來) preprocessing2(把plan切開)處理完

In [20]:
test_data = pd.read_csv('/storage/kdd/test_final3.csv')#這個檔案就是去除no_plan no_pid剩下的data

In [21]:
test_data

,sid,pid,req_time,o,d,plan_time,plans,p0,p1,p2,...,price9,eta9,mode10,dis10,price10,eta10,mode11,dis11,price11,eta11
0,1126541,178395.0,2018-12-05 14:51:43,"116.41,39.92","116.46,39.95",2018-12-05 14:51:43,"[{""distance"": 13610, ""price"": 400, ""eta"": 2388...",0.0,0.0,0.0,...,400,2387,0,0,0,0,0,0,0,0
1,1389752,178395.0,2018-12-03 17:30:22,"116.40,39.91","116.46,39.95",2018-12-03 17:30:22,"[{""distance"": 10499, ""price"": 400, ""eta"": 2946...",0.0,0.0,0.0,...,400,2888,0,0,0,0,0,0,0,0
2,1126543,178395.0,2018-12-05 12:10:43,"116.41,39.92","116.32,39.89",2018-12-05 12:10:43,"[{""distance"": 12277, ""price"": 400, ""eta"": 2319...",0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,1349248,178395.0,2018-12-04 09:42:37,"116.41,39.91","116.46,39.95",2018-12-04 09:42:37,"[{""distance"": 9710, ""price"": 400, ""eta"": 2270,...",0.0,0.0,0.0,...,400,2449,0,0,0,0,0,0,0,0
4,1349239,178395.0,2018-12-04 22:49:10,"116.32,39.89","116.41,39.92",2018-12-04 22:49:10,"[{""distance"": 10475, ""price"": 4000, ""eta"": 194...",0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
5,1349241,178395.0,2018-12-04 09:34:17,"116.41,39.91","116.30,39.92",2018-12-04 09:34:17,"[{""distance"": 12438, ""price"": 400, ""eta"": 2247...",0.0,0.0,0.0,...,400,2194,0,0,0,0,0,0,0,0
6,1126542,178395.0,2018-12-05 12:08:39,"116.41,39.92","116.46,39.95",2018-12-05 12:08:39,"[{""distance"": 13758, ""price"": 400, ""eta"": 2519...",0.0,0.0,0.0,...,400,2520,0,0,0,0,0,0,0,0
7,1349243,178395.0,2018-12-04 09:13:49,"116.41,39.91","116.30,39.92",2018-12-04 09:13:49,"[{""distance"": 12738, ""price"": 1800, ""eta"": 257...",0.0,0.0,0.0,...,400,2846,1,12738,1800,2579,0,0,0,0
8,1349244,178395.0,2018-12-04 10:05:37,"116.31,39.91","116.29,39.92",2018-12-04 10:05:37,"[{""distance"": 3245, ""price"": 300, ""eta"": 1137,...",0.0,0.0,0.0,...,300,1119,0,0,0,0,0,0,0,0
9,1126540,178395.0,2018-12-05 15:24:34,"116.46,39.95","116.46,39.95",2018-12-05 15:24:34,"[{""distance"": 458, ""price"": """", ""eta"": 391, ""t...",0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
10,1349240,178395.0,2018-12-04 08:51:50,"116.41,39.92","116.29,39.92",2018-12-04 08:51:50,"[{""distance"": 13856, ""price"": 500, ""eta"": 2860...",0.0,0.0,0.0,...,500,2842,0,0,0,0,0,0,0,0
11,453685,179178.0,2018-12-01 12:50:33,"116.39,39.90","116.41,39.91",2018-12-01 12:50:33,"[{""distance"": 2858, ""price"": 200, ""eta"": 1798,...",1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
12,1107620,179178.0,2018-12-05 13:11:30,"116.57,39.91","116.48,39.88",2018-12-05 13:11:30,"[{""distance"": 12615, ""price"": 400, ""eta"": 2650...",1.0,0.0,0.0,...,400,2474,1,15182,1800,2463,0,0,0,0
13,1107621,179178.0,2018-12-05 17:37:08,"116.47,39.89","116.31,39.67",2018-12-05 17:37:08,"[{""distance"": 37332, ""price"": 700, ""eta"": 3962...",1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
14,1107618,179178.0,2018-12-05 13:14:29,"116.57,39.91","116.48,39.88",2018-12-05 13:14:29,"[{""distance"": 12583, ""price"": 400, ""eta"": 2621...",1.0,0.0,0.0,...,400,2445,1,15150,1800,2428,0,0,0,0
15,1349032,179178.0,2018-12-04 22:12:58,"116.30,39.62","116.29,39.87",2018-12-04 22:12:58,"[{""distance"": 34150, ""price"": """", ""eta"": 2078,...",1.0,0.0,0.0,...,0,0,0,0,0,0,1,40056,800,5915
16,1437724,179178.0,2018-12-06 14:29:56,"116.40,39.97","116.41,39.96",2018-12-06 14:29:56,"[{""distance"": 1348, ""price"": """", ""eta"": 1171, ...",1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
17,2066073,184748.0,2018-12-07 10:17:35,"116.37,39.71","116.31,39.89",2018-12-07 10:17:35,"[{""distance"": 33453, ""price"": 800, ""eta"": 5624...",1.0,0.0,0.0,...,0,0,1,33101,2800,4507,0,0,0,0
18,452746,162795.0,2018-12-01 07:52:44,"116.33,39.97","116.31,39.98",2018-12-01 07:52:44,"[{""distance"": 4007, ""price"": 1500, ""eta"": 989,...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
19,452745,162795.0,2018-12-01 07:57:29,"116.32,39.96","116.31,39.98",2018-12-01 07:57:29,"[{""distance"": 2650, ""price"": 300, ""eta"": 961, ...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
20,1431672,116384.0,2018-12-06 10:36:30,"116.51,39.68","116.51,39.68",2018-12-06 10:36:30,"[{""distance"": 692, ""price"": """", ""eta"": 591, ""t...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
21,2060796,116384.0,2018-12-07 15:57:48,"116.42,39.82","116.42,39.82",2018-12-07 15:57:48,"[{""distance"": 864, ""price"": """", ""eta"": 740, ""t...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
22,2060799,116384.0,2018-12-07 14:51:03,"116.41,39.91","116.41,39.84",2018-12-07 14:51:03,"[{""distance"": 10487, ""price"": 400, ""eta"": 1994...",0.0,0.0,1.0,...,400,1904,0,0,0,0,0,0,0,0
23,1431678,116384.0,2018-12-06 09:09:51,"116.44,39.84","116.51,39.68",2018-12-06 09:09:51,"[{""distance"": 24286, ""price"": 2900, ""eta"": 517...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
24,2060795,116384.0,2018-12-07 08:46:50,"116.65,40.13","116.31,39.98",2018-12-07 08:46:50,"[{""distance"": 43240, ""price"": 700, ""eta"": 5135...",0.0,0.0,1.0,...,0,0,1,42981,3100,5017,0,0,0,0
25,1431680,116384.0,2018-12-06 07:55:19,"116.43,39.85","116.31,39.98",2018-12-06 07:55:19,"[{""distance"": 27894, ""price"": 600, ""eta"": 4549...",0.0,0.0,1.0,...,600,4021,1,27835,1900,4317,0,0,0,0
26,2060792,116384.0,2018-12-07 15:44:03,"116.42,39.84","116.42,39.82",2018-12-07 15:44:03,"[{""distance"": 4413, ""price"": 200, ""eta"": 1840,...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
27,2060797,116384.0,2018-12-07 09:37:00,"116.40,40.00","116.31,39.97",2018-12-07 09:37:00,"[{""distance"": 11058, ""price"": 400, ""eta"": 2134...",0.0,0.0,1.0,...,0,0,1,11630,1900,2067,0,0,0,0
28,1128839,116384.0,2018-12-05 22:42:57,"116.59,40.08","116.51,39.68",2018-12-05 22:42:57,"[{""distance"": 60445, ""price"": """", ""eta"": 3998,...",0.0,0.0,1.0,...,0,0,1,62584,10800,5777,0,0,0,0
29,1128838,116384.0,2018-12-05 22:43:20,"116.59,40.08","116.51,39.68",2018-12-05 22:43:20,"[{""distance"": 60445, ""price"": """", ""eta"": 4000,...",0.0,0.0,1.0,...,0,0,1,62584,10800,5778,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61728,1419477,128755.0,2018-12-06 08:55:25,"116.29,39.95","116.44,39.96",2018-12-06 08:55:25,"[{""distance"": 19825, ""price"": 500, ""eta"": 3113...",0.0,0.0,0.0,...,500,2849,0,0,0,0,0,0,0,0
61729,1413463,148040.0,2018-12-06 21:59:42,"116.49,39.93","116.34,39.90",2018-12-06 21:59:42,"[{""distance"": 17660, ""price"": 700, ""eta"": 4541...",0.0,0.0,0.0,...,500,3659,0,0,0,0,0,0,0,0
61730,1123701,133261.0,2018-12-05 09:43:10,"116.42,40.07","116.49,40.14",2018-12-05 09:43:10,"[{""distance"": 12349, ""price"": 400, ""eta"": 3723...",0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
61731,1393550,176518.0,2018-12-03 19:27:37,"116.39,39.98","116.40,39.93",2018-12-03 19:27:37,"[{""distance"": 7038, ""price"": 400, ""eta"": 1402,...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
61732,1415669,216654.0,2018-12-06 12:06:45,"116.64,40.34","116.59,40.92",2018-12-06 12:06:45,"[{""distance"": 87930, ""price"": """", ""eta"": 5486,...",0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
61733,1108383,103104.0,2018-12-05 21:53:43,"116.46,39.94","116.47,39.93",2018-12-05 21:53:43,"[{""distance"": 2449, ""price"": 200, ""eta"": 1807,...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
61734,1279336,161440.0,2018-12-02 09:05:42,"116.34,39.71","116.42,39.90",2018-12-02 09:05:42,"[{""distance"": 30671, ""price"": 800, ""eta"": 5450...",0.0,0.0,0.0,...,0,0,1,30165,1900,4366,0,0,0,0
61735,1423005,188097.0,2018-12-06 14:24:31,"116.40,40.00","116.32,39.89",2018-12-06 14:24:31,"[{""distance"": 23618, ""price"": 500, ""eta"": 4315...",0.0,0.0,0.0,...,500,3983,0,0,0,0,0,0,0,0
61736,1428031,104975.0,2018-12-06 15:23:43,"116.28,39.80","116.33,39.90",2018-12-06 15:23:43,"[{""distance"": 22596, ""price"": 600, ""eta"": 8587...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
61737,1437258,203066.0,2018-12-06 20:45:58,"116.35,39.84","116.33,39.89",2018-12-06 20:45:58,"[{""distance"": 10916, ""price"": 400, ""eta"": 2235...",0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
61738,1255824,187471.0,2018-12-02 14:03:35,"116.63,40.05","116.51,39.92",2018-12-02 14:03:35,"[{""distance"": 35486, ""price"": 800, ""eta"": 6416...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
61739,2037790,121018.0,2018-12-07 17:13:32,"116.40,39.95","116.40,39.95",2018-12-07 17:13:32,"[{""distance"": 362, ""price"": """", ""eta"": 308, ""t...",0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
61740,430543,180567.0,2018-12-01 09:38:27,"116.42,39.73","116.40,39.76",2018-12-01 09:38:27,"[{""distance"": 5634, ""price"": 1400, ""eta"": 1018...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
61741,1438109,103961.0,2018-12-06 18:49:53,"116.43,39.94","116.37,39.86",2018-12-06 18:49:53,"[{""distance"": 14088, ""price"": 500, ""eta"": 2236...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
61742,1400878,166754.0,2018-12-03 22:58:01,"116.56,39.79","116.49,39.79",2018-12-03 22:58:01,"[{""distance"": 8426, ""price"": 3300, ""eta"": 1574...",1.0,0.0,0.0,...,400,2296,0,0,0,0,0,0,0,0
61743,1410511,207359.0,2018-12-06 22:12:18,"116.37,39.98","116.86,40.37",2018-12-06 22:12:18,"[{""distance"": 79407, ""price"": """", ""eta"": 3761,...",0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
61744,1123391,192931.0,2018-12-05 12:56:04,"116.56,40.22","116.42,39.90",2018-12-05 12:56:04,"[{""distance"": 55332, ""price"": 1100, ""eta"": 884...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
61745,1334930,153397.0,2018-12-04 22:01:58,"116.63,40.12","116.65,40.12",2018-12-04 22:01:58,"[{""distance"": 3790, ""price"": 1400, ""eta"": 644,...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
61746,2053193,161567.0,2018-12-07 21:52:24,"116.27,39.91","116.34,39.92",2018-12-07 21:52:24,"[{""distance"": 9610, ""price"": 600, ""eta"": 2587,...",0.0,0.0,1.0,...,400,2375,0,0,0,0,0,0,0,0
61747,1143957,170839.0,2018-12-05 11:07:25,"116.45,39.91","116.34,39.91",2018-12-05 11:07:25,"[{""distance"": 11179, ""price"": 400, ""eta"": 2017...",1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
61748,1361900,102295.0,2018-12-04 10:29:46,"116.39,39.95","116.36,39.92",2018-12-04 10:29:46,"[{""distance"": 7049, ""price"": 300, ""eta"": 2081,...",0.0,0.0,0.0,...,300,1845,0,0,0,0,0,0,0,0
61749,459896,204610.0,2018-12-01 08:26:25,"116.44,39.92","116.41,39.95",2018-12-01 08:26:25,"[{""distance"": 6924, ""price"": 300, ""eta"": 2051,...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
61750,1344076,106860.0,2018-12-04 15:30:11,"116.39,39.79","116.61,39.92",2018-12-04 15:30:11,"[{""distance"": 36216, ""price"": 800, ""eta"": 5791...",1.0,0.0,0.0,...,0,0,1,33172,3000,4337,0,0,0,0
61751,1329537,153660.0,2018-12-04 12:55:39,"116.76,39.75","116.50,39.84",2018-12-04 12:55:39,"[{""distance"": 52044, ""price"": 1300, ""eta"": 979...",0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
61752,1393464,113473.0,2018-12-03 18:58:58,"116.63,40.30","116.63,40.30",2018-12-03 18:58:58,"[{""distance"": 608, ""price"": """", ""eta"": 519, ""t...",0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
61753,1342497,151896.0,2018-12-04 15:29:38,"116.40,39.98","116.39,39.78",2018-12-04 15:29:38,"[{""distance"": 33164, ""price"": 800, ""eta"": 5578...",0.0,0.0,1.0,...,0,0,1,33352,2900,4400,0,0,0,0
61754,1337980,105821.0,2018-12-04 10:40:45,"116.28,39.92","116.42,39.96",2018-12-04 10:40:45,"[{""distance"": 19272, ""price"": 700, ""eta"": 4459...",0.0,0.0,0.0,...,500,3759,1,27037,1800,3920,0,0,0,0
61755,1448860,171910.0,2018-12-06 11:54:12,"116.36,40.06","116.24,40.05",2018-12-06 11:54:12,"[{""distance"": 14437, ""price"": 600, ""eta"": 5536...",0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
61756,1253699,209130.0,2018-12-02 15:31:17,"116.23,40.18","116.23,40.22",2018-12-02 15:31:17,"[{""distance"": 5486, ""price"": 200, ""eta"": 1884,...",0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
61757,1273922,143335.0,2018-12-02 07:48:52,"116.38,39.95","116.59,40.08",2018-12-02 07:48:52,"[{""distance"": 34070, ""price"": 2800, ""eta"": 402...",0.0,0.0,1.0,...,2900,4219,0,0,0,0,0,0,0,0

In [23]:
test_data_sid = test_data.sid.values

test_data = test_data.drop(columns= ['sid','pid','plans','req_time','plan_time','o','d'])
test_data = test_data.drop(columns = ['time_hour'])

from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
test_data = scaler.fit_transform(test_data)
test_data = pd.DataFrame(test_data)

In [24]:
test_data

,0,1,2,3,4,5,6,7,8,9,...,104,105,106,107,108,109,110,111,112,113
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.12500,0.256860,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.12500,0.310772,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.12500,0.263532,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
5,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.12500,0.236092,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
6,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.12500,0.271172,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
7,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.12500,0.306252,1.0,0.127057,0.157895,0.278751,0.0,0.000000,0.000000,0.000000
8,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.09375,0.120413,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
9,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
10,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.15625,0.305822,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
11,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
12,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.12500,0.266222,1.0,0.151435,0.157895,0.266213,0.0,0.000000,0.000000,0.000000
13,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
14,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.12500,0.263101,1.0,0.151116,0.157895,0.262430,0.0,0.000000,0.000000,0.000000
15,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,1.0,0.241607,0.235294,0.374984
16,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
17,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.00000,0.000000,1.0,0.330171,0.245614,0.487138,0.0,0.000000,0.000000,0.000000
18,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
19,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
20,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
21,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
22,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.12500,0.204885,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
23,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
24,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,1.0,0.428721,0.271930,0.542261,0.0,0.000000,0.000000,0.000000
25,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.18750,0.432691,1.0,0.277645,0.166667,0.466602,0.0,0.000000,0.000000,0.000000
26,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
27,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,1.0,0.116005,0.166667,0.223411,0.0,0.000000,0.000000,0.000000
28,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,1.0,0.624254,0.947368,0.624406,0.0,0.000000,0.000000,0.000000
29,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,1.0,0.624254,0.947368,0.624514,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61728,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.15625,0.306575,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61729,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.15625,0.393737,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61730,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61731,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61732,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61733,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61734,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,1.0,0.300886,0.166667,0.471898,0.0,0.000000,0.000000,0.000000
61735,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.15625,0.428602,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61736,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61737,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61738,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61739,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61740,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61741,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61742,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.12500,0.247068,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61743,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61744,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61745,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61746,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.12500,0.255569,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61747,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61748,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.09375,0.198537,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61749,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61750,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.00000,0.000000,1.0,0.330880,0.263158,0.468764,0.0,0.000000,0.000000,0.000000
61751,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61752,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61753,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.00000,0.000000,1.0,0.332675,0.254386,0.475573,0.0,0.000000,0.000000,0.000000
61754,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.15625,0.404498,1.0,0.269685,0.157895,0.423692,0.0,0.000000,0.000000,0.000000
61755,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61756,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
61757,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.90625,0.453998,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000

In [26]:
from sklearn.externals import joblib #jbolib模块

rf = joblib.load('rf.pkl')

In [27]:
test_label = rf.predict(test_data)
len(test_label)

61758

In [31]:
a= pd.DataFrame({'sid': test_data_sid, 'recommend_mode':test_label})
a = a[['sid','recommend_mode']]
a

           sid  recommend_mode
0      1126541               2
1      1389752               2
2      1126543               2
3      1349248               2
4      1349239               2
5      1349241               2
6      1126542               2
7      1349243               2
8      1349244               2
9      1126540               5
10     1349240               2
11      453685               6
12     1107620               2
13     1107621               2
14     1107618               2
15     1349032              11
16     1437724               5
17     2066073              10
18      452746               2
19      452745               2
20     1431672               5
21     2060796               5
22     2060799               2
23     1431678               7
24     2060795               2
25     1431680               2
26     2060792               1
27     2060797               2
28     1128839               7
29     1128838               7
...        ...             ...
61728  1419477               2
61729  1413463               9
61730  1123701               1
61731  1393550               2
61732  1415669               1
61733  1108383               1
61734  1279336              10
61735  1423005               2
61736  1428031               1
61737  1437258               2
61738  1255824               7
61739  2037790               5
61740   430543               1
61741  1438109               2
61742  1400878               9
61743  1410511               7
61744  1123391               7
61745  1334930               1
61746  2053193               9
61747  1143957               2
61748  1361900               9
61749   459896               2
61750  1344076               7
61751  1329537               7
61752  1393464               5
61753  1342497               7
61754  1337980               9
61755  1448860               1
61756  1253699               1
61757  1273922               2

[61758 rows x 2 columns]

In [32]:
test_merges1 = pd.read_csv('/storage/kdd/test_final.csv')
total_sid = test_merges1.sid.values

In [34]:
total = pd.DataFrame({'sid': total_sid})
total

           sid
0      1126541
1      1389752
2      1126543
3      1349248
4      1349239
5      1349241
6      1126542
7      1349243
8      1349244
9      1126540
10     1349240
11      453685
12     1107620
13     1107621
14     1107618
15     1349032
16     1437724
17     2066073
18      452746
19      452745
20     1431672
21     2060796
22     2060799
23     1431678
24     2060795
25     1431680
26     2060792
27     2060797
28     1128839
29     1128838
...        ...
94328  1393550
94329  1415669
94330  1108383
94331  1279336
94332  1423005
94333  1428031
94334  1437258
94335   437239
94336  1255824
94337  2037790
94338   430543
94339  1438109
94340  1400878
94341  1410511
94342  2046228
94343  1123391
94344  1334930
94345  2053193
94346  1143957
94347  1361900
94348   459896
94349  1344076
94350  1329537
94351  1393464
94352  1342497
94353  1337980
94354  1448860
94355  1253699
94356  1273922
94357  1338573

[94358 rows x 1 columns]

In [37]:
#把三個連起來 主要是a會改變 其餘2個不會
c = pd.concat([no_plan_data,no_pid_data ,a], ignore_index= True)

In [38]:
c

           sid recommend_mode
0      1109845              0
1      2043193              0
2      2067285              0
3      1263692              0
4      1141190              0
5      1344396              0
6      1130573              0
7       459267              0
8      1274977              0
9      1109837              0
10      467774              0
11     2059899              0
12     2059752              0
13     1117277              0
14     2038995              0
15     1397613              0
16     1260661              0
17     1271091              0
18     1253690              0
19     1357035              0
20     1348981              0
21     1388021              0
22     1348564              0
23     2049957              0
24     1351268              0
25     1331526              0
26      424384              0
27     1145329              0
28     1331620              0
29     1355716              0
...        ...            ...
94328  1419477              2
94329  1413463              9
94330  1123701              1
94331  1393550              2
94332  1415669              1
94333  1108383              1
94334  1279336             10
94335  1423005              2
94336  1428031              1
94337  1437258              2
94338  1255824              7
94339  2037790              5
94340   430543              1
94341  1438109              2
94342  1400878              9
94343  1410511              7
94344  1123391              7
94345  1334930              1
94346  2053193              9
94347  1143957              2
94348  1361900              9
94349   459896              2
94350  1344076              7
94351  1329537              7
94352  1393464              5
94353  1342497              7
94354  1337980              9
94355  1448860              1
94356  1253699              1
94357  1273922              2

[94358 rows x 2 columns]

In [39]:
aa = total.merge(c,left_on='sid',right_on='sid')
aa

           sid recommend_mode
0      1126541              2
1      1389752              2
2      1126543              2
3      1349248              2
4      1349239              2
5      1349241              2
6      1126542              2
7      1349243              2
8      1349244              2
9      1126540              5
10     1349240              2
11      453685              6
12     1107620              2
13     1107621              2
14     1107618              2
15     1349032             11
16     1437724              5
17     2066073             10
18      452746              2
19      452745              2
20     1431672              5
21     2060796              5
22     2060799              2
23     1431678              7
24     2060795              2
25     1431680              2
26     2060792              1
27     2060797              2
28     1128839              7
29     1128838              7
...        ...            ...
94328  1393550              2
94329  1415669              1
94330  1108383              1
94331  1279336             10
94332  1423005              2
94333  1428031              1
94334  1437258              2
94335   437239              0
94336  1255824              7
94337  2037790              5
94338   430543              1
94339  1438109              2
94340  1400878              9
94341  1410511              7
94342  2046228              0
94343  1123391              7
94344  1334930              1
94345  2053193              9
94346  1143957              2
94347  1361900              9
94348   459896              2
94349  1344076              7
94350  1329537              7
94351  1393464              5
94352  1342497              7
94353  1337980              9
94354  1448860              1
94355  1253699              1
94356  1273922              2
94357  1338573              0

[94358 rows x 2 columns]

In [40]:
aa.to_csv('rftest.csv' , index = False)