In [1]:
import pandas as pd
import numpy as np
import os
import math
import csv
import random
import time
import collections
from tqdm import tqdm_notebook as tqdm

In [2]:
# train_final = pd.read_csv('/storage/kdd/train_final.csv')
train_final = pd.read_csv('/storage/kdd/test_final2.csv')

In [3]:
plans = train_final.plans

In [4]:
plans = plans.values

In [5]:
plans

array(['[{"distance": 13610, "price": 400, "eta": 2388, "transport_mode": 2}, {"distance": 8228, "price": "", "eta": 1929, "transport_mode": 3}, {"distance": 8228, "price": 2800, "eta": 2169, "transport_mode": 4}, {"distance": 9175, "price": 400, "eta": 2387, "transport_mode": 9}, {"distance": 8267, "price": "", "eta": 2499, "transport_mode": 6}, {"distance": 8506, "price": 500, "eta": 3287, "transport_mode": 7}]',
       '[{"distance": 10499, "price": 400, "eta": 2946, "transport_mode": 2}, {"distance": 11179, "price": "", "eta": 2137, "transport_mode": 3}, {"distance": 11179, "price": 4300, "eta": 2377, "transport_mode": 4}, {"distance": 9323, "price": "", "eta": 2817, "transport_mode": 6}, {"distance": 10282, "price": 400, "eta": 2888, "transport_mode": 9}, {"distance": 10124, "price": 400, "eta": 5048, "transport_mode": 1}]',
       '[{"distance": 12277, "price": 400, "eta": 2319, "transport_mode": 2}, {"distance": 13769, "price": "", "eta": 2875, "transport_mode": 3}, {"distance": 13769, "price": 3300, "eta": 2935, "transport_mode": 4}]',
       ...,
       '[{"distance": 14437, "price": 600, "eta": 5536, "transport_mode": 1}, {"distance": 13942, "price": "", "eta": 1790, "transport_mode": 3}, {"distance": 13942, "price": 3700, "eta": 2090, "transport_mode": 4}, {"distance": 15177, "price": 400, "eta": 5675, "transport_mode": 1}]',
       '[{"distance": 5486, "price": 200, "eta": 1884, "transport_mode": 1}, {"distance": 5866, "price": "", "eta": 692, "transport_mode": 3}, {"distance": 5866, "price": 1700, "eta": 992, "transport_mode": 4}, {"distance": 4661, "price": "", "eta": 1409, "transport_mode": 6}, {"distance": 5959, "price": 200, "eta": 2266, "transport_mode": 1}, {"distance": 4654, "price": "", "eta": 4186, "transport_mode": 5}]',
       '[{"distance": 34070, "price": 2800, "eta": 4026, "transport_mode": 2}, {"distance": 26697, "price": "", "eta": 2037, "transport_mode": 3}, {"distance": 26697, "price": 6200, "eta": 2337, "transport_mode": 4}, {"distance": 35924, "price": 2900, "eta": 4219, "transport_mode": 9}, {"distance": 29227, "price": 2700, "eta": 5300, "transport_mode": 1}]'],
      dtype=object)

In [6]:
#先測試plans[0]切出來長怎樣
# fea = []
# a = plans[0].replace('""','0')
# a = a.replace('"','')
# a = a.replace('},','')
# a = a.replace('}','')
# a = a.replace('[','')
# a = a.replace(']','')
# a = a.split('{')

In [7]:
# a

In [8]:
test = []
for num in tqdm(range(len(plans))):
    fea = []
    #處理str 把文字拿掉只取值出來
    ary = plans[num].replace('""','1')
    ary = ary.replace('"','')
    ary = ary.replace('},','')
    ary = ary.replace('}','')
    ary = ary.replace('[','')
    ary = ary.replace(']','')
    ary = ary.replace('distance: ',',')
    ary = ary.replace(' price: ','')
    ary = ary.replace(' eta: ','')
    ary = ary.replace(' transport_mode: ','')
    ary = ary.replace('{','')
    ary = ary.replace(' ','')
    ary = ary.split(',')
    #丟掉ary[0] = '' 這個值 把其餘正確的值append到fea內
    for i in range(len(ary)-1):
        fea.append(int(ary[i+1]))
    #建立正確的值順序以便待會丟入pandas    
    pla = [0]*44 #缺值全0
    #缺值補最大值
#     pla = [0,212163,15000,72992,
#            0,92247,3400,11083,
#            0,206865,0,14529,
#            0,206865,92300,14769,
#            0,5000,0,4708,
#            0,10000,0,3027,
#            0,225864,13100,72638,
#            0,182949,20400,15726,
#            0,90860,3300,10432,
#            0,98894,12800,10433,
#            0,161480,5600,21022]
    
    #將pla 把所有數據放好  之後直接轉pandas
    for i in range(3,len(fea),4):
        
        #有重複的推薦mode則放入第一個重複的推薦
        mode = fea[i]
        if(pla[4*(mode-1)] == 0):  #多加這行
            pla[4*(mode-1)] = 1
            pla[4*(mode-1) +1] = fea[i-3]
            pla[4*(mode-1) +2] = fea[i-2]
            pla[4*(mode-1) +3] = fea[i-1]

    test.append(pla)
    del fea,ary,pla

HBox(children=(IntProgress(value=0, max=61758), HTML(value='')))

In [9]:
type(test)

list

In [10]:
data = pd.DataFrame(test,columns=['mode1', 'dis1', 'price1', 'eta1',
                                'mode2', 'dis2', 'price2', 'eta2',
                                'mode3', 'dis3', 'price3', 'eta3',
                                'mode4', 'dis4', 'price4', 'eta4',
                                'mode5', 'dis5', 'price5', 'eta5',
                                'mode6', 'dis6', 'price6', 'eta6',
                                'mode7', 'dis7', 'price7', 'eta7',
                                'mode8', 'dis8', 'price8', 'eta8',
                                'mode9', 'dis9', 'price9', 'eta9',
                                'mode10', 'dis10', 'price10', 'eta10',
                                'mode11', 'dis11', 'price11', 'eta11'])

In [11]:
data

,mode1,dis1,price1,eta1,mode2,dis2,price2,eta2,mode3,dis3,...,price9,eta9,mode10,dis10,price10,eta10,mode11,dis11,price11,eta11
0,0,0,0,0,1,13610,400,2388,1,8228,...,400,2387,0,0,0,0,0,0,0,0
1,1,10124,400,5048,1,10499,400,2946,1,11179,...,400,2888,0,0,0,0,0,0,0,0
2,0,0,0,0,1,12277,400,2319,1,13769,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,9710,400,2270,1,11571,...,400,2449,0,0,0,0,0,0,0,0
4,0,0,0,0,1,12268,400,2366,1,10475,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,1,12438,400,2247,1,12235,...,400,2194,0,0,0,0,0,0,0,0
6,0,0,0,0,1,13758,400,2519,1,10708,...,400,2520,0,0,0,0,0,0,0,0
7,1,11786,400,4243,1,13995,500,2979,1,12827,...,400,2846,1,12738,1800,2579,0,0,0,0
8,1,3174,200,1527,1,3245,300,1137,1,2838,...,300,1119,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,1,803,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,1,13856,500,2860,1,13288,...,500,2842,0,0,0,0,0,0,0,0
11,1,2858,200,1798,0,0,0,0,1,2562,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,1,12615,400,2650,1,12144,...,400,2474,1,15182,1800,2463,0,0,0,0
13,0,0,0,0,1,37332,700,3962,1,38421,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,1,12583,400,2621,1,16177,...,400,2445,1,15150,1800,2428,0,0,0,0
15,1,34307,800,6653,0,0,0,0,1,34150,...,0,0,0,0,0,0,1,40056,800,5915
16,0,0,0,0,0,0,0,0,1,2231,...,0,0,0,0,0,0,0,0,0,0
17,1,28018,600,6514,0,0,0,0,1,27460,...,0,0,1,33101,2800,4507,0,0,0,0
18,1,4154,200,2328,1,3705,300,1867,1,4007,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,1,2650,300,961,1,2495,...,0,0,0,0,0,0,0,0,0,0
20,1,691,200,937,0,0,0,0,1,694,...,0,0,0,0,0,0,0,0,0,0
21,1,1679,200,1388,0,0,0,0,1,3888,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,1,10487,400,1994,1,10203,...,400,1904,0,0,0,0,0,0,0,0
23,1,26336,600,7041,0,0,0,0,1,26772,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,1,43240,700,5135,1,44220,...,0,0,1,42981,3100,5017,0,0,0,0
25,0,0,0,0,1,27894,600,4549,1,26470,...,600,4021,1,27835,1900,4317,0,0,0,0
26,1,4413,200,1840,0,0,0,0,1,4309,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,1,11058,400,2134,1,11255,...,0,0,1,11630,1900,2067,0,0,0,0
28,1,59457,3200,10003,0,0,0,0,1,60445,...,0,0,1,62584,10800,5777,0,0,0,0
29,1,59457,3200,10002,0,0,0,0,1,60445,...,0,0,1,62584,10800,5778,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61728,1,16476,300,4163,1,19825,500,3113,1,16861,...,500,2849,0,0,0,0,0,0,0,0
61729,0,0,0,0,0,0,0,0,1,16014,...,500,3659,0,0,0,0,0,0,0,0
61730,1,12349,400,3723,0,0,0,0,1,13749,...,0,0,0,0,0,0,0,0,0,0
61731,0,0,0,0,1,7038,400,1402,1,6272,...,0,0,0,0,0,0,0,0,0,0
61732,1,89840,1900,9210,0,0,0,0,1,87930,...,0,0,0,0,0,0,0,0,0,0
61733,1,2449,200,1807,0,0,0,0,1,2197,...,0,0,0,0,0,0,0,0,0,0
61734,0,0,0,0,0,0,0,0,1,31573,...,0,0,1,30165,1900,4366,0,0,0,0
61735,1,20402,400,5267,1,23618,500,4315,1,23163,...,500,3983,0,0,0,0,0,0,0,0
61736,1,22596,600,8587,0,0,0,0,1,16112,...,0,0,0,0,0,0,0,0,0,0
61737,1,8303,200,2944,1,10916,400,2235,1,8330,...,0,0,0,0,0,0,0,0,0,0
61738,1,25523,600,6431,0,0,0,0,1,22216,...,0,0,0,0,0,0,0,0,0,0
61739,0,0,0,0,0,0,0,0,1,3849,...,0,0,0,0,0,0,0,0,0,0
61740,1,6991,200,2268,0,0,0,0,1,5634,...,0,0,0,0,0,0,0,0,0,0
61741,0,0,0,0,1,14088,500,2236,1,16382,...,0,0,0,0,0,0,0,0,0,0
61742,1,12517,1700,3957,0,0,0,0,1,8426,...,400,2296,0,0,0,0,0,0,0,0
61743,1,80298,1800,8323,0,0,0,0,1,79407,...,0,0,0,0,0,0,0,0,0,0
61744,1,49689,1100,10383,0,0,0,0,1,45207,...,0,0,0,0,0,0,0,0,0,0
61745,1,7975,200,3597,0,0,0,0,1,3790,...,0,0,0,0,0,0,0,0,0,0
61746,1,8401,400,3089,0,0,0,0,1,8932,...,400,2375,0,0,0,0,0,0,0,0
61747,0,0,0,0,1,11179,400,2017,1,11821,...,0,0,0,0,0,0,0,0,0,0
61748,1,5574,200,2319,1,7049,300,2081,1,7272,...,300,1845,0,0,0,0,0,0,0,0
61749,1,6279,200,2405,1,6924,300,2051,1,5861,...,0,0,0,0,0,0,0,0,0,0
61750,0,0,0,0,0,0,0,0,1,32196,...,0,0,1,33172,3000,4337,0,0,0,0
61751,1,49600,1100,10541,0,0,0,0,1,29333,...,0,0,0,0,0,0,0,0,0,0
61752,0,0,0,0,0,0,0,0,1,3798,...,0,0,0,0,0,0,0,0,0,0
61753,0,0,0,0,0,0,0,0,1,33821,...,0,0,1,33352,2900,4400,0,0,0,0
61754,1,16240,500,5193,0,0,0,0,1,18256,...,500,3759,1,27037,1800,3920,0,0,0,0
61755,1,14437,600,5536,0,0,0,0,1,13942,...,0,0,0,0,0,0,0,0,0,0
61756,1,5486,200,1884,0,0,0,0,1,5866,...,0,0,0,0,0,0,0,0,0,0
61757,1,29227,2700,5300,1,34070,2800,4026,1,26697,...,2900,4219,0,0,0,0,0,0,0,0

In [12]:
final = pd.concat([train_final, data], axis = 1)

In [13]:
final.head()

,sid,pid,req_time,o,d,plan_time,plans,p0,p1,p2,...,price9,eta9,mode10,dis10,price10,eta10,mode11,dis11,price11,eta11
0,1126541,178395.0,2018-12-05 14:51:43,"116.41,39.92","116.46,39.95",2018-12-05 14:51:43,"[{""distance"": 13610, ""price"": 400, ""eta"": 2388...",0.0,0.0,0.0,...,400,2387,0,0,0,0,0,0,0,0
1,1389752,178395.0,2018-12-03 17:30:22,"116.40,39.91","116.46,39.95",2018-12-03 17:30:22,"[{""distance"": 10499, ""price"": 400, ""eta"": 2946...",0.0,0.0,0.0,...,400,2888,0,0,0,0,0,0,0,0
2,1126543,178395.0,2018-12-05 12:10:43,"116.41,39.92","116.32,39.89",2018-12-05 12:10:43,"[{""distance"": 12277, ""price"": 400, ""eta"": 2319...",0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,1349248,178395.0,2018-12-04 09:42:37,"116.41,39.91","116.46,39.95",2018-12-04 09:42:37,"[{""distance"": 9710, ""price"": 400, ""eta"": 2270,...",0.0,0.0,0.0,...,400,2449,0,0,0,0,0,0,0,0
4,1349239,178395.0,2018-12-04 22:49:10,"116.32,39.89","116.41,39.92",2018-12-04 22:49:10,"[{""distance"": 10475, ""price"": 4000, ""eta"": 194...",0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
# final.to_csv('/storage/kdd/train_final2.csv', index = False)
final.to_csv('/storage/kdd/test_final3.csv', index = False)